
// This file has been generated by the GUI designer. Do not modify.
namespace Home.AppGtk
{
	public partial class LoginView
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Button button3;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Entry entry1;

		private global::Gtk.Entry entry2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Home.AppGtk.LoginView
			this.Name = "Home.AppGtk.LoginView";
			this.Title = global::Mono.Unix.Catalog.GetString("LoginView");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Home.AppGtk.LoginView.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button3 = new global::Gtk.Button();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.fixed1.Add(this.button3);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button3]));
			w1.X = 260;
			w1.Y = 171;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w2.X = 154;
			w2.Y = 112;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("label2");
			this.fixed1.Add(this.label2);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
			w3.X = 153;
			w3.Y = 144;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry1 = new global::Gtk.Entry();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '●';
			this.fixed1.Add(this.entry1);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry1]));
			w4.X = 212;
			w4.Y = 100;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry2 = new global::Gtk.Entry();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '●';
			this.fixed1.Add(this.entry2);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry2]));
			w5.X = 211;
			w5.Y = 138;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 273;
			this.Show();
		}
	}
}
