// <auto-generated />
namespace Home.Repository.HOME_SQL
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V1_0_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V1_0_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201704180313142_V1_0_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
