// <auto-generated />
namespace Home.Repository.HOME_SQL
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class V1_3_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V1_3_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201712110731053_V1_3_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
